layout_spectrum: 0.5909945671446621
typography_spectrum: 0.746316333534196
color:
  brandStrength: 0.08452925132587552
  lightness: 0.07267612940631807
  saturation: 0.12549794325605035
  rhythmicContrast: 0.5737094306387007
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
name: Sky Fury Studios
